name: Release Spark Version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-spark'

jobs:
  build-and-release:
    name: Build and Release Spark Theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, json, dom
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Install NPM Dependencies
        run: npm install

      - name: Run Linting Checks
        run: npm run lint

      - name: Build Assets
        run: npm run build

      - name: Prepare Release Title
        id: prep
        run: |
          # Example: v1.0.0-spark -> Spark v1.0.0
          TAG=${{ github.ref_name }}
          VERSION=$(echo $TAG | sed -e 's/^v//' -e 's/-spark$//')
          TITLE="Spark v$VERSION"
          echo "release_title=$TITLE" >> $GITHUB_ENV

      - name: Bump Theme Version
        run: |
          THEME_VERSION=$(echo "${{ github.ref_name }}" | sed -e 's/^v//' -e 's/-spark$//')
          sed -i "s/Version: .*/Version: $THEME_VERSION/" style.css

      - name: Find and Replace Theme Name
        run: |
          find . -type f \( -name "*.php" -o -name "style.css" \) -exec sed -i 's/Pulsar/Spark/g' {} +
          find . -type f \( -name "*.php" -o -name "style.css" \) -exec sed -i 's/pulsar/spark/g' {} +
          sed -i "s/Description: .*/Description: The bespoke theme for our Spark projects./" style.css

      - name: Replace Theme Screenshot
        run: curl -L "${{ secrets.SPARK_SCREENSHOT_URL }}" -o screenshot.png

      - name: Create Zip Archive
        run: |
          zip -r spark.zip . -x ".git/*" ".github/*" ".playground/*" "node_modules/*" ".editorconfig" ".gitignore" "package-lock.json" "package.json" "src/*" "phpcs.xml" "webpack.config.js" "composer.json" "composer.lock" "vendor/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.release_title }}
          files: spark.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
