name: Release Spark Version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-spark'

jobs:
  build-and-release:
    name: Build and Release Spark Theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Prepare Clean Tag, Version, and Release Title
        id: prep
        run: |
          TAG=${{ github.ref_name }}
          CLEAN_TAG=$(echo "$TAG" | sed -e 's/-spark$//')
          VERSION=$(echo "$CLEAN_TAG" | sed -e 's/^v//')
          TITLE="Spark v$VERSION"
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "tag=$CLEAN_TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Bump Theme Version
        run: |
          sed -i "s/Version: .*/Version: ${{ steps.prep.outputs.version }}/" style.css

      - name: Find and Replace All Theme References
        run: |
          # 1. Replace the general 'Pulsar' name (e.g., in PHP class names)
          find . -type f -name "*.php" -exec sed -i 's/Pulsar/Spark/g' {} +

          # 2. Specifically handle the pattern slugs first
          find . -type f -name "*.php" -exec sed -i 's/"slug":"pulsar\//\"slug\":\"spark\//g' {} +

          # 3. Now, replace all other lowercase 'pulsar' instances (like text domains)
          find . -type f -name "*.php" -exec sed -i 's/pulsar/spark/g' {} +

          # 4. Update the theme header in style.css
          sed -i -e 's/Theme Name:.*Pulsar/Theme Name:       Spark/' \
                 -e 's/Text Domain:.*pulsar/Text Domain:     spark/' \
                 -e "s/Description: .*/Description: ${{ secrets.SPARK_DESCRIPTION }}/" style.css

          # 5. Update the package name in composer.json
          sed -i 's|"eighteen73/pulsar"|"eighteen73/spark"|g' composer.json

      - name: Replace Theme Screenshot
        run: curl -L "${{ secrets.SPARK_SCREENSHOT_URL }}" -o screenshot.png

      - name: Push to GitHub Distribution Repository
        env:
          DEPLOY_KEY: ${{ secrets.SPARK_DEPLOY_KEY }}
          GIT_USER: ${{ secrets.GIT_COMMIT_USER || 'GitHub Actions' }}
          GIT_EMAIL: ${{ secrets.GIT_COMMIT_EMAIL || 'actions@github.com' }}
        run: |
          CLEAN_TAG=${{ steps.prep.outputs.tag }}

          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          echo "Configuring Git..."
          git config --global user.name "${GIT_USER}"
          git config --global user.email "${GIT_EMAIL}"

          echo "Cloning destination repository..."
          git clone git@github.com:eighteen73/spark.git ../spark-dist

          echo "Syncing files to destination..."
          rsync -av --delete . ../spark-dist/ \
            --exclude ".editorconfig" \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".gitignore" \
            --exclude ".playground" \
            --exclude "config/theme-json" \
            --exclude "node_modules" \
            --exclude "src" \
            --exclude "vendor" \
            --exclude "package.json" \
            --exclude "package-lock.json" \
            --exclude "phpcs.xml" \
            --exclude "webpack.config.js"

          cd ../spark-dist

          echo "Committing, tagging, and pushing..."
          git add .

          if ! git diff --staged --quiet; then
            git commit -m "Release $CLEAN_TAG"
          else
            echo "No changes to commit."
          fi

          git tag -f $CLEAN_TAG

          echo "Pushing to destination..."
          git push origin main
          git push origin $CLEAN_TAG --force
